# 告警级别分类：
# 紧急告警( critical ):P0
# 警告告警( warning ):P1
# 信息告警( info ):P2

global:
  resolve_timeout: 5m

templates:
  - /etc/prometheus/conf.d/email.tmpl

inhibit_rules:
  - source_match:  # 严重抑制警告
      severity: critical
    target_match:
      severity: warning
    equal: [ all, alertname ]
  - source_match: ## 节点失联抑制进程退出
      alertname: 节点失联
    target_match:
      alertname: 进程退出
    equal: [ all ]

route:
  group_by: ['alertname','job']
  group_wait: 3m
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'blackhole'
  routes:
  - receiver: "@linux/feishu"
    match_re: { channels: "(.*)?@linux/feishu([:/;].*)?" }
    continue: true
    routes:
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:15m.*" }
      repeat_interval: 15m
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:30m.*" }
      repeat_interval: 30m
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:1h.*" }
      repeat_interval: 1h
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:2h.*" }
      repeat_interval: 2h
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:4h.*" }
      repeat_interval: 4h

receivers:
  - name: "blackhole"
  - name: '@linux/feishu'
    webhook_configs:
      - url: 'http://10.1.1.24:8080/prometheusalert?type=fs&tpl=prometheus-fsv2'
        send_resolved: true
