global:
  resolve_timeout: 5m

#templates:
#  - /etc/prometheus/conf.d/*.tmpl

inhibit_rules:
  - source_match:
      severity: error
    target_match:
      severity: warning
    equal: [ all, alertname ]

route:
  group_by: ['alertname','job']
  group_wait: 3m
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'blackhole'
  routes:
  - receiver: "@linux/feishu"
    match_re: { channels: "(.*)?@linux/feishu([:/;].*)?" }
    continue: true
    routes:
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:15m.*" }
      repeat_interval: 15m
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:30m.*" }
      repeat_interval: 30m
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:1h.*" }
      repeat_interval: 1h
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:2h.*" }
      repeat_interval: 2h
    - receiver: "@linux/feishu"
      match_re: { channels: ".*@linux/feishu:4h.*" }
      repeat_interval: 4h

receivers:
  - name: "blackhole"
  - name: '@linux/feishu'
    webhook_configs:
      - url: 'http://10.1.1.24:8080/prometheusalert?type=fs&tpl=prometheus-fsv2'
        send_resolved: true
