---
- name: config /etc/system/system.conf
  lineinfile:
    path: /etc/system/system.conf
    line: "{{ item }}"
  with_items:
    - DefaultLimitNOFILE=1048576

- name: config /etc/security/limits.conf
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - * soft nofile 1048576
    - * hard nofile 1048576

- name: config /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - fs.file-max=2097152
    - fs.nr_open=2097152
    - net.core.somaxconn=65535
    - net.ipv4.tcp_max_syn_backlog=65536
    - net.core.netdev_max_backlog=32768
    - net.ipv4.ip_local_port_range='1000 65535'
    - net.core.rmem_default=262144
    - net.core.wmem_default=262144
    - net.core.rmem_max=16777216
    - net.core.wmem_max=16777216
    - net.core.optmem_max=16777216
    - net.ipv4.tcp_rmem='1024 4096 16777216'
    - net.ipv4.tcp_wmem='1024 4096 16777216'
    - net.nf_conntrack_max=1000000
    - net.netfilter.nf_conntrack_max=1000000
    - net.netfilter.nf_conntrack_tcp_timeout_time_wait=30
    - net.ipv4.tcp_max_tw_buckets=1048576
    - net.ipv4.tcp_fin_timeout=15
