---
## backuppc {{{
backuppc_idrsapub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1tSCA9p7Po61wrIPohoAsOhULSuQv5oMElAI0Ws4FwS5LXYDw4NxGByhlbthI04vPlXAlgbQ0/Bqmf5L8OUvZdKYSCMyVqPEgQ2s1dCz5UdTHH4AkjlZQwxG3AaG4QiFumoYy9G4fzc92/iX3ORGjFCQtykTEd0Tjw45sr8nznZ47YKi4Ztk0Zpoh1EloYcRbefSwc6hAwWXFEj0NJiBtR0tfORS0AOGBDvNOwkeI0faWGJ7zKZTebVwfCqZypUU/gsW9YNkk1OZNhT7sUmX6nSjVxsMN/1rE1YswlhFRSeWCQCCwB3xUQW53925elJPt+2DRs9YvS5px+nVCcPR7Lk6C6a44cswkCrbVc2kcjF5Ovio+WiFinTp61ibD5kKXKGFSCqIU4FPNZbikkyS1WUtsULy6PzZEDFzjumWKzciUUDOgLlnBBUZX1wOjrvO0WXOCJLMR6PIikfuhcmVJjE+CWkxJbOUrTvvBv6Z28D4y9MqEKqatZQZRIrgI6rs= backuppc@backuppc
#}}}

## mysqld_exporter {{{
#先创建用于采集指标的用户并赋予权限
#CREATE USER 'exporter'@'%' IDENTIFIED BY 'export-123' WITH MAX_USER_CONNECTIONS 3;
#GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
mysqld_exporter_username: exporter
mysqld_exporter_password: exporter-123
#}}}

## vmware_exporter # {{{
vmware_username: root
vmware_password: root-123
#}}}

## emqx {{{
emq_username: exporter
emq_password: public
##}}}
