- name: create config file
  block:
    - template:
        src: ifcfg-eth0.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ interface }}
        mode: 0644

    - service:
        name: network
        state: restarted
  when: ansible_os_family == "RedHat"
