---
- name: config oh-my-zsh theme # {{{
  lineinfile:
    dest: ~{{ username }}/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="{{ zsh_theme }}"'
    owner: "{{ username }}"
    group: "{{ groupname }}"
  # }}}

- name: Remove oh-my-zsh default plugin configuration # {{{ | 配置zsh插件
  lineinfile:
    dest: ~{{ username }}/.zshrc
    regexp: '^plugins='
    owner: "{{ username }}"
    group: "{{ groupname }}"
    state: absent

- name: Configure the list of plugins loaded by zsh
  blockinfile:
    path: ~{{ username }}/.zshrc
    insertbefore: "^source"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    block: |
      plugins=(
              git
              zsh-autosuggestions
              zsh-syntax-highlighting
              zsh-completions
              z
              history-substring-search
              command-not-found
              colored-man-pages
              extract
              history-search-multi-word
              fast-syntax-highlighting
              bundler
              macos
              rake
              ruby
      )
  # }}}

- name: Configure keyboard support # {{{
  lineinfile:
    dest: ~{{ username }}/.zshrc
    owner: "{{ username }}"
    group: "{{ groupname }}"
    line: "{{ item }}"
  with_items:
    - '# key bindings'
    - 'bindkey "\e[1~" beginning-of-line'
    - 'bindkey "\e[4~" end-of-line'
    - 'bindkey "\e[5~" beginning-of-history'
    - 'bindkey "\e[6~" end-of-history'
    - '# for rxvt'
    - 'bindkey "\e[8~" end-of-line'
    - 'bindkey "\e[7~" beginning-of-line'
    - "# for non RH/Debian xterm, can't hurt for RH/DEbian xterm"
    - 'bindkey "\eOH" beginning-of-line'
    - 'bindkey "\eOF" end-of-line'
    - '# for freebsd console'
    - 'bindkey "\e[H" beginning-of-line'
    - 'bindkey "\e[F" end-of-line'
    - '# completion in the middle of a line'
    - "bindkey '^i' expand-or-complete-prefix"
    - '# Fix numeric keypad'
    - '# 0 . Enter'
    - 'bindkey -s "^[Op" "0"'
    - 'bindkey -s "^[On" "."'
    - 'bindkey -s "^[OM" "^M"'
    - '# 1 2 3'
    - 'bindkey -s "^[Oq" "1"'
    - 'bindkey -s "^[Or" "2"'
    - 'bindkey -s "^[Os" "3"'
    - '# 4 5 6'
    - 'bindkey -s "^[Ot" "4"'
    - 'bindkey -s "^[Ou" "5"'
    - 'bindkey -s "^[Ov" "6"'
    - '# 7 8 9'
    - 'bindkey -s "^[Ow" "7"'
    - 'bindkey -s "^[Ox" "8"'
    - 'bindkey -s "^[Oy" "9"'
    - '# + - * /'
    - 'bindkey -s "^[Ol" "+"'
    - 'bindkey -s "^[Om" "-"'
    - 'bindkey -s "^[Oj" "*"'
    - 'bindkey -s "^[Oo" "/"'
# }}}
