---
- stat:
    path: ~{{ username }}/.oh-my-zsh
  register: oh_my_zsh

# 正常情况下，在国内无法直接下载这个文件，所以我把它放在本地了，见下方copy模块
#- name: Download install.sh
#  get_url:
#    url: "{{ zsh_installer_url }}"
#    dest: /tmp/install.sh
#    mode: 0755
#    owner: "{{ username }}"
#    group: "{{ groupname }}"
#  when: oh_my_zsh.stat.exists == false

- name: Copy install.sh
  copy:
    src: files/install.sh
    dest: /tmp/install.sh
    mode: 0755
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Install oh-my-zsh
  shell: su - "{{ username }}" -s /bin/bash /tmp/install.sh
  ignore_errors: true
  when: oh_my_zsh.stat.exists == false
