---
- stat: # {{{
    path: "{{ plugins_path }}/zsh-syntax-highlighting"
  register: zsh_syntax_highlighting

- stat:
    path: "{{ plugins_path }}/zsh-autosuggestions"
  register: zsh_autosuggestions

- stat:
    path: "{{ plugins_path }}/zsh-completions"
  register: zsh_completions

- stat:
    path: "{{ plugins_path }}/zsh-history-substring-search"
  register: zsh_history_substring_search

- stat:
    path: "{{ plugins_path }}/history-search-multi-word"
  register: history_search_multi_word

- stat:
    path: "{{ plugins_path }}/fast-syntax-highlighting"
  register: fast_syntax_highlighting
# }}}

- name: 安装zsh-syntax-highlighting:模仿fish命令行高亮的插件 # {{{
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ plugins_path }}/zsh-syntax-highlighting"
    clone: yes
    update: yes
  when: zsh_syntax_highlighting.stat.exists == false
  # }}}

- name: 安装zsh-autosuggestions:根据命令历史记录自动推荐和提示的插件 # {{{
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ plugins_path }}/zsh-autosuggestions"
    clone: yes
    update: yes
  when: zsh_autosuggestions.stat.exists == false
  # }}}

- name: 安装zsh-completions:自动命令补全，类似bash-completions功能的插件 # {{{
  git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: "{{ plugins_path }}/zsh-completions"
    clone: yes
    update: yes
  when: zsh_completions.stat.exists == false
  # }}}

- name: history-substring-search:按住向上箭头可以搜索出现过该关键字的历史命令 # {{{
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search
    dest: "{{ plugins_path }}/zsh-history-substring-search"
    clone: yes
    update: yes
  when: zsh_history_substring_search.stat.exists == false
  # }}}

- name: history-search-multi-word:ctrl+r搜索历史记录 # {{{
  git:
    repo: https://github.com/zdharma-continuum/history-search-multi-word
    dest: "{{ plugins_path }}/history-search-multi-word"
    clone: yes
    update: yes
  when: history_search_multi_word.stat.exists == false
  # }}}

- name: fast-syntax-highlighting:丰富的语法高亮 # {{{
  git:
    repo: https://github.com/zdharma-continuum/fast-syntax-highlighting
    dest: "{{ plugins_path }}/fast-syntax-highlighting"
    clone: yes
    update: yes
  when: fast_syntax_highlighting.stat.exists == false
  # }}}

