---
- name: config hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "{{ hostvars['mfsmaster'].ansible_host }} mfsmaster"
    - "{{ hostvars['mfs-master'].ansible_host }} mfs-master"
    - "{{ hostvars['mfs-slaver'].ansible_host }} mfs-slaver"
    - "{{ hostvars['mfs-chunkserver-1'].ansible_host }} mfs-chunkserver-1"
    - "{{ hostvars['mfs-chunkserver-2'].ansible_host }} mfs-chunkserver-2"
    - "{{ hostvars['mfs-chunkserver-3'].ansible_host }} mfs-chunkserver-3"

- name: install mfs chunkserver
  package:
    name: moosefs-chunkserver
    state: latest

- name: config chunkserver
  lineinfile:
    path: /etc/mfs/mfschunkserver.cfg
    regexp: "^# MASTER_HOST"
    line: "MASTER_HOST = mfsmaster"

- name: create hdd dir
  file:
    path: "{{ item }}"
    state: directory
    owner: mfs
    group: mfs
    mode: 0755
    recurse: false
  with_items:
    - /mnt/mfs1
    - /mnt/mfs2

- name: config hdd
  lineinfile:
    path: /etc/mfs/mfshdd.cfg
    line: "{{ item }}"
  with_items:
    - /mnt/mfs1
    - /mnt/mfs2

- name: start mfs service
  service:
    name: moosefs-chunkserver
    state: started
    enabled: yes

- name: config firewalld for redhat
  block:
    - shell: firewall-cmd --add-port={{ item }}/tcp --permanent
      with_items:
        - 9422

    - shell: firewall-cmd --reload
  when: ansible_os_family == "RedHat"
