---
- name: 准备vim插件文件夹 # {{{
  file:
    path: ~{{ username }}/.vim/{{ item }}
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0755
  with_items:
    - plugged
    - autoload
    - bundle
  # }}}

- name: 安装vim-plug插件管理器 # {{{
  stat:
    path: ~{{ username }}/.vim/autoload/plug.vim
  register: plug_vim

- get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~{{ username }}/.vim/autoload/plug.vim
    mode: 0644
    owner: "{{ username }}"
    group: "{{ groupname }}"
  when: plug_vim.stat.exists == false
  # }}}

- stat: # {{{ | 安装airline插件
    path: ~{{ username }}/.vim/plugged/vim-airline
  register: vim_airline

- stat:
    path: ~{{ username }}/.vim/plugged/vim-airline-themes
  register: vim_airline_themes

- git:
    repo: https://github.com/vim-airline/vim-airline
    dest: ~{{ username }}/.vim/plugged/vim-airline
    clone: yes
    update: yes
  when: vim_airline.stat.exists == false

- git:
    repo: https://github.com/vim-airline/vim-airline-themes
    dest: ~{{ username }}/.vim/plugged/vim-airline-themes
    clone: yes
    update: yes
  when: vim_airline_themes.stat.exists == false
  # }}}

- stat: # {{{ | 安装自动提示插件
    path: ~{{ username }}/.vim/bundle/Vundle.vim
  register: vundle_vim

- stat:
    path: ~{{ username }}/.vim/bundle/YouCompleteMe
  register: youcompleteme

- git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~{{ username }}/.vim/bundle/Vundle.vim
    clone: yes
    update: yes
  when: vundle_vim.stat.exists == false

- git:
    repo: https://github.com/Valloric/YouCompleteMe.git
    dest: ~{{ username }}/.vim/bundle/YouCompleteMe
    clone: yes
    update: yes
    recursive: yes
  ignore_errors: yes
  when: youcompleteme.stat.exists == false

- shell: ~{{ username }}/.vim/bundle/YouCompleteMe/install.py --all --verbose
  ignore_errors: yes
  when: youcompleteme.stat.exists == true
  # }}}

- stat: # {{{ | 安装缩进线插件
    path: ~{{ username }}/.vim/bundle/indentLine
  register: indent_line

- git:
    repo: https://github.com/Yggdroot/indentLine.git
    dest: ~{{ username }}/.vim/bundle/indentLine
    clone: yes
    update: yes
    recursive: yes
  ignore_errors: true
  when: indent_line.stat.exists == false
  # }}}
