---

backuppc_server_name: "{{ ansible_hostname }}"
backuppc_fetch_ssh_key: false
backuppc_local_fetch_dir: "./fetch"
backuppc_hosts: []

#
# Global configuration
#
backuppc_ServerPort: -1
backuppc_ServerMesgSecret: ''
backuppc_MaxBackups: 4
backuppc_MaxUserBackups: 4
backuppc_MaxBackupPCNightlyJobs: 2
backuppc_BackupPCNightlyPeriod: 1
backuppc_MaxOldLogFiles: 14
backuppc_FullPeriod: 6.97
backuppc_IncrPeriod: 0.97
backuppc_PingMaxMsec: 200
backuppc_XferLogLevel: 1

# Rsync
backuppc_RsyncClientCmd: '$sshPath -q -x -l root $host $rsyncPath $argList+'
backuppc_RsyncClientRestoreCmd: '$sshPath -q -x -l root $host $rsyncPath $argList+'
