---
- name: start nacos-mysql
  block:
    - shell: docker-compose -f {{ nacos_mysql_root_dir }}/docker-compose.yml up -d
  when: inventory_hostname == "nacos-mysql"

- name: start nacos-app
  block:
    - shell: docker-compose -f {{ nacos_app_root_dir }}/docker-compose.yml up -d
  when: not inventory_hostname == "nacos-proxy"

- name: show docker container status
  block:
    - shell: docker ps -a | grep "nacos-app\|nacos-mysql"
      register: docker_status

    - debug:
        msg: "{{ inventory_hostname }}:{{ docker_status.stdout_lines }}"
  when: not inventory_hostname == "nacos-proxy"

- name: open metrics
  block:
    - shell: |
        docker exec nacos-app echo "management.endpoints.web.exposure.include=*" >> /home/nacos/conf/application.properties
        docker restart nacos-app
      when: not inventory_hostname == "nacos-proxy" and open_metrics == true
