---
- name: 集中备份账号 # {{{
  hosts: all:!off
  tasks:
    - authorized_key:
        user: root
        state: present
        key: "{{ backuppc_idrsapub }}"
    - known_hosts:
        name: '{{ ansible_host }}'
        key: '{{ ansible_host }} ecdsa-sha2-nistp256 {{ ansible_ssh_host_key_ecdsa_public | default(ansible_ssh_host_key_rsa_public) }}'
      become: true
      become_user: backuppc
      delegate_to: backuppc-server
# }}}

- hosts: all:!off
  vars_files:
    - files/backuppc_vars.yml
  vars:
    backuppc_instance: '{{ extension | selectattr("hostname","equalto", inventory_hostname) | list }}'
  tasks:
    - block: # {{{ debug
      - name: 配置南京备份服务器 (亚洲)
        tags: never, debug
        debug:
          msg: '{{ backuppc_instance }}'
        delegate_to: backuppc-server
     # }}}

    - name: 配置备份服务器
      import_role:
        name: roles/leif160519.backuppc
      delegate_to: backuppc-server
