##
# 安装基础软件
#
#
##
# @leif160519 @2020.08.29
# 默认配置用户为root，其他用户请跟参数-e username=ubuntu -e groupname=root
####
---
- name: 1.Configure ssh  # {{{
  hosts: all:!off
  tags: config, ssh
  tasks:
    - block:
        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^(#|)UseDNS'
            line: 'UseDNS no'

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^(#|)GSSAPIAuthentication'
            line: 'GSSAPIAuthentication no'

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^(#|)ClientAliveInterval'
            line: 'ClientAliveInterval 60'

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^(#|)ClientAliveCountMax'
            line: 'ClientAliveCountMax 60'

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: "^(#|)PermitRootLogin"
            line: "PermitRootLogin without-password"

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: "^(#|)PasswordAuthentication"
            line: "PasswordAuthentication yes"

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: "^(#|)PermitEmptyPasswords"
            line: "PermitEmptyPasswords no"

        - lineinfile:
            dest: /etc/ssh/ssh_config
            regexp: '^(#|)   StrictHostKeyChecking'
            line: '    StrictHostKeyChecking no'

        - lineinfile:
            path: /etc/ssh/ssh_config
            line: "{{ item }}"
          with_items:
            - "    ServerAliveInterval 20"
            - "    ServerAliveCountMax 999"

        - lineinfile:
            dest: /etc/ssh/ssh_config
            regexp: "    GSSAPIAuthentication yes"
            line: "    GSSAPIAuthentication no"

        - service:
            name: sshd
            state: reloaded
  # }}}

- name: 2.Configure hostname & hosts # {{{
  hosts: all:!off
  tags: config, host
  tasks:
    - block:
        - name: configure hostname
          hostname:
            name: "{{ inventory_hostname }}"

        - name: configure hosts
          template:
            src: files/hosts.j2
            dest: /etc/hosts
  # }}}

- name: 3.Masking system error reports # {{{
  hosts: all:!off
  tags: config, error
  tasks:
    - block:
        - file:
            path: /var/crash/
            state: absent
          when: ansible_distribution == "Ubuntu"

        - lineinfile:
            dest: /etc/default/apport
            regexp: '^enabled='
            line: 'enabled=0'
          when: ansible_distribution == "Ubuntu"
  # }}}

- name: 4.Configure sudoer privileges # {{{
  hosts: all:!off
  tags: config, sudo
  vars:
    username: root
    groupname: root
  tasks:
    - block:
        - name: config sudo privileges
          lineinfile:
            dest: /etc/sudoers.d/{{ username }}
            create: yes
            line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
            mode: 0440
            owner: root
            group: root
            validate: /usr/sbin/visudo -cf %s
          when: not ( username is match "root" )

        - name: config sudo log
          block:
            - file:
                path: /var/log/sudo.log
                state: touch
                owner: root
                group: root
                mode: 0644

            - lineinfile:
                path: /etc/rsyslog.conf
                line: "local2.debug /var/log/sudo.log"

            - lineinfile:
                path: /etc/sudoers
                line: "{{ item }}"
              with_items:
                - Defaults logfile=/var/log/sudo.log
                - Defaults loglinelen=0
                - Defaults !syslog

            - service:
                name: rsyslog
                state: restarted
  # }}}

- name: 5.Disable selinux # {{{
  hosts: all:!off
  tags: config, seliux
  tasks:
    - block:
        - lineinfile:
            dest: /etc/selinux/config
            regexp: '^SELINUX='
            line: 'SELINUX=disabled'
          when: ansible_os_family == "RedHat"

        - name: effective immediately
          shell: setinforce 0
          ignore_errors: yes
          when: ansible_os_family == "RedHat"
  # }}}

- name: 6.Disable firewall #{{{
  hosts: all:!off
  tags: config, firewall
  tasks:
    - block:
        - name: stop firewalld service
          service:
            name: firewalld
            state: stopped
            enabled: no
          when: ansible_os_family == "RedHat"
  # }}}

- name: 7.Configure pip # {{{
  hosts: all:!off
  tags: never, pip, python
  vars:
    username: root
    groupname: root
  tasks:
    - block:
        - name: create .pip directory
          file:
            path: ~{{ username }}/.pip
            state: directory
            owner: "{{ username }}"
            group: "{{ groupname }}"
            mode: 0755

        - name: generate configuration file
          blockinfile:
            path: ~{{ username }}/.pip/pip.conf
            create: yes
            owner: "{{ username }}"
            group: "{{ groupname }}"
            block: |
              [global]
              index-url = http://mirrors.aliyun.com/pypi/simple/
              [install]
              trusted-host=mirrors.aliyun.com
  # }}}

- name: 8.Configure shutdown wait time  # {{{
  hosts: all:!off
  tags: config, shutdown
  tasks:
    - block:
        - lineinfile:
            dest: /etc/systemd/system.conf
            regexp: "^(#|)DefaultTimeoutStartSec"
            line: "DefaultTimeoutStartSec=10s"

        - lineinfile:
            dest: /etc/systemd/system.conf
            regexp: "^(#|)DefaultTimeoutStopSec"
            line: "DefaultTimeoutStopSec=10s"
  # }}}

- name: 9.Open cron log # {{{
  hosts: all:!off
  tags: config, cron
  tasks:
    - block:
        - replace:
            path: /etc/rsyslog.d/50-default.conf
            regexp: "#cron"
            replace: "cron"
          when: ansible_distribution == "Ubuntu"

        - replace:
            path: /etc/rsyslog.conf
            regexp: "#cron"
            replace: "cron"
          when: (ansible_distribution == "Debian") or (ansible_os_family == "RedHat")

        - service:
            name: rsyslog
            state: restarted
            enabled: yes
  # }}}

- name: 10.Configure bash # {{{
  hosts: all:!off
  tags: config, bash
  vars:
    username: root
    groupname: root
  tasks:
    - block:
        - file:
            path: /etc/bash.d
            state: directory

        - template:
            src: files/bash.d/bash-ps1.sh.j2
            dest: /etc/bash.d/bash-ps1.sh
            force: yes
            mode: 0755
            owner: root
            group: root

        - copy:
            src: "{{ item }}"
            dest: /etc/bash.d/
            mode: 0755
            owner: root
            group: root
          with_fileglob:
            - "files/bash.d/*.sh"

        - blockinfile:
            dest: "/etc/profile"
            block: |
              if [ -d /etc/bash.d ]; then
                for i in /etc/bash.d/*.sh; do
                  if [ -r $i ]; then
                    . $i
                  fi
                done
                unset i
              fi

  # }}}

- name: 11.Configure clock & time zone # {{{
  hosts: all:!off
  tags: config, clock, time
  tasks:
    - block:
        - timezone:
            hwclock: UTC
            name: Asia/Shanghai
  # }}}

- name: 12.Configure the default editor # {{{
  hosts: all:!off
  tags: config, editor
  vars:
    username: root
    groupname: root
  tasks:
    - block:
        - lineinfile:
            dest: "~{{ username }}/.selected_editor"
            create: yes
            mode: 0644
            owner: "{{ username }}"
            group: "{{ groupname }}"
            line: 'SELECTED_EDITOR="/usr/bin/vim.basic"'
            state: present
          # }}}

- name: 13.Rewrite cron templates  # {{{
  hosts: all:!off
  tags: config, cron
  vars:
    username: root
    groupname: root
  tasks:
    - block:
        - template:
            dest: "/var/spool/cron/crontabs/{{ username }}"
            src: files/crontab
            mode: 0600
            owner: "{{ username }}"
            group: crontab
          ignore_errors: yes
          when: ansible_os_family == "Debian"

        - template:
            dest: "/var/spool/cron/{{ username }}"
            src: files/crontab
            mode: 0600
            owner: "{{ username }}"
            group: "{{ username }}"
          ignore_errors: yes
          when: ansible_os_family == "RedHat"
         # }}}

- name: 14.Configure git #{{{
  hosts: all:!off
  tags: config, git
  tasks:
    - block:
        - template:
            src: files/gitconfig.j2
            dest: /root/.gitconfig
            owner: root
            group: root
            mode: 0644
  # }}}

- name: 15.Uninstall useless kernel # {{{
  hosts: os.ubuntu
  tags: never, kernel
  tasks:
    - block:
        - name: get the kernel version number currently in use
          shell: /bin/uname -r | sed 's/-generic//g'
          register: current_version

        - name: get the kernel software that needs to be uninstalled
          shell: /usr/bin/dpkg -l | grep "linux-image\|linux-headers\|linux-modules" | awk '{print $2}' | grep -v "{{ current_version.stdout }}" | cat
          register: before

        - name: configure dpkg
          shell: /usr/bin/dpkg --configure -a

        - name: clean up useless kernels
          shell: /usr/bin/dpkg -l | grep "linux-image\|linux-headers\|linux-modules" | awk '{print $2}' | grep -v linux-image-generic | grep -v linux-headers-generic | grep -v "{{ current_version.stdout }}" | xargs apt-get -y purge
          ignore_errors: yes
          when: not (before.stdout == "")

        - name: clean up residue
          shell: apt-get autoremove --purge -y

        - name: update grub
          shell: /usr/sbin/update-grub

        - name: get the cleaned kernel
          shell: /usr/bin/dpkg -l | grep "linux-image\|linux-headers\|linux-modules" | awk '{print $2}'
          register: after

        - name: disable kernel update
          shell: /usr/bin/dpkg -l | grep "linux-image\|linux-headers\|linux-modules" | awk '{print $2}' | xargs /usr/bin/apt-mark hold
          register: hold_result

        - name: disable auto upgrades
          file:
            src: /usr/share/unattended-upgrades/20auto-upgrades-disabled
            dest: /etc/apt/apt.conf.d/20auto-upgrades-disabled
            state: link
        - blockinfile:
            create: true
            path: /etc/apt/apt.conf.d/50package-blacklist
            block: |
              Unattended-Upgrade::Package-Blacklist {
                      "linux-headers*";
                      "linux-image*";
                      "linux-generic*";
                      "linux-modules*";
              }

        - debug:
            var: after.stdout_lines

        - debug:
            var: hold_result.stdout_lines
      when: ansible_distribution == "Ubuntu"
  # }}}

- name: 16.Disable system update # {{{
  hosts: os.ubuntu
  tags: never, update
  tasks:
    - block:
        - name: close Update-Package-Lists
          shell: sed -i.bak 's/1/0/' /etc/apt/apt.conf.d/10periodic

        - name: close unattended-upgrades (or `dpkg-reconfigure unattended-upgrades` choose `no`)
          shell: sed -i.bak 's/1/0/' /etc/apt/apt.conf.d/20auto-upgrades

        - name: disable unattended-upgrades service
          service:
            name: unattended-upgrades
            state: stopped
            enabled: false

        - name: remove unattended-upgrades service
          package:
            name: unattended-upgrades
            state: absent

      when: ansible_distribution == "Ubuntu"
# }}}

- name: 17.Disable install snapd # {{{
  hosts: os.debian
  tags: never, snap
  tasks:
    - block:
        - blockinfile:
            path: /etc/apt/preferences.d/nosnap.pref
            block: |
              Package: snap*
              Pin: release a=*
              Pin-Priority: -10
            create: yes
            mode: 0644
            owner: root
            group: root
# }}}

- name: 18.You have new mail. # {{{
  hosts: all:!off
  tags: config, mail
  tasks:
    - block:
        - shell: ls /var/mail/
          register: file_list

        - file:
            path: "/var/mail/{{ item }}"
            state: absent
          with_items:
            - "{{ file_list.stdout_lines }}"
# }}}

- name: 19.create sshkey # {{{
  hosts: all:!off
  vars:
    username: root
    groupname: root
  tags: never, sshkey
  tasks:
    - block:
        - user:
            name: "{{ username }}"
            comment: "{{ username }}"
            group: "{{ groupname }}"
            generate_ssh_key: yes
            ssh_key_file: ~{{ item }}/.ssh/id_rsa
            state: present
          ignore_errors: yes
# }}}

- name: 20.config resolv # {{{
  hosts: all:!off
  tags: never, resolv
  roles:
    - role: roles/ahuffman.resolv
      resolv_nameservers:
        - 180.76.76.76
        - 114.114.114.114
      resolv_domain: localdomain
      resolv_search:
        - localdomain
      resolv_options:
        - timeout:2
        - rotate
# }}}

- name: 21.config static ip address # {{{
  hosts: all:!off
  tags: never, network
  vars:
    dns1: 180.76.76.76
    dns2: 114.114.114.114
    search: localdomain
  roles:
    - role: roles/leif160519.network
# }}}

- name: 22.config ntp # {{{
  # 注意：ubuntu20.04的系统请将ansible版本升级至2.9.8以上或使用2.10(使用pip3而不是apt)，详情参看：https://github.com/geerlingguy/ansible-role-ntp/issues/86
  hosts: all:!off
  tags: never, ntp
  roles:
    - role: roles/geerlingguy.ntp
      ntp_enabled: true
      ntp_timezone: "Asia/Shanghai"
      ntp_manage_config: true
      ntp_servers:
        - "ntp{{ '.' + ntp_area if ntp_area else '' }}.aliyun.com"
        - "ntp1{{ '.' + ntp_area if ntp_area else '' }}.aliyun.com"
        - "ntp2{{ '.' + ntp_area if ntp_area else '' }}.aliyun.com"
        - "ntp3{{ '.' + ntp_area if ntp_area else '' }}.aliyun.com"
      ntp_restrict:
        - "127.0.0.1"
        - "::1"
      ntp_cron_handler_enabled: true
      ntp_tinker_panic: true
# }}}

- name: 23.config ulimit # {{{
  hosts: all:!off
  tags: config, ulimit
  tasks:
    - block:
        - lineinfile:
            dest: /etc/security/limits.conf
            line: "{{ item }}"
          with_items:
            - "*　　soft　　nofile　　65536"
            - "*　　hard　　nofile　　65536"
            - "*    soft    noproc    65535"
            - "*    hard    noproc    65535"
# }}}

- name: 24.config sysctl # {{{
  hosts: all:!off
  tags: config, sysctl
  tasks:
    - block:
        - lineinfile:
            path: /etc/sysctl.conf
            line: "{{ item }}"
          with_items:
            - fs.file-max = 1000000
            - net.ipv4.tcp_tw_reuse = 1
            - net.ipv4.tcp_keepalive_time = 600
            - net.ipv4.tcp_fin_timeout = 30
            - net.ipv4.tcp_max_tw_buckets = 5000
            - net.ipv4.ip_local_port_range = 1024 6500
            - net.ipv4.tcp_rmem = 10240 87380 12582912
            - net.ipv4.tcp_wmem = 10240 87380 12582912
            - net.core.netdev_max_backlog = 8096
            - net.core.rmem_default = 6291456
            - net.core.wmem_default = 6291456
            - net.core.rmem_max = 12582912
            - net.core.wmem_max = 12582912
            - net.ipv4.tcp_syncookies = 1
            - net.ipv4.tcp_max_syn_backlog = 8192
            - net.ipv4.tcp_tw_recycle = 1
            - net.core.somaxconn=262114
            - net.ipv4.tcp_max_orphans=262114
# }}}
