##
# 安装gitlab
#
#
##
# @leif160519 @2020.08.29
# 官方包下载地址:https://packages.gitlab.com/gitlab/gitlab-ce
# Quick install:
#     curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
#     curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
####
---
- name: 安装gitlab
  hosts: gitlab-server
  tags: [gitlab]
  environment: "{{ proxy_env }}"
  vars:
    gitlab_rpm_version: gitlab-ce-13.12.8-ce.0.el7.x86_64
    gitlab_rpm_url: https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/{{ gitlab_rpm_version }}.rpm/download.rpm
    gitlab_deb_version: gitlab-ce_13.12.8-ce.0_amd64
    gitlab_deb_url: https://packages.gitlab.com/gitlab/gitlab-ce/packages/{{ ansible_lsb.id | lower }}/{{ ansible_lsb.codename }}/{{ gitlab_deb_version }}.deb/download.deb
  tasks:
    - block:
        - stat:
            path: /bin/gitlab-ctl
          register: gitlab_cmd

        - yum:
            name: "{{ gitlab_rpm_url }}"
            state: present
          when: (ansible_machine=="x86_64") and (gitlab_cmd.stat.exists == false) and (ansible_os_family == "RedHat")

        - apt:
            deb: "{{ gitlab_deb_url }}"
            state: present
          when: (ansible_machine=="x86_64") and (gitlab_cmd.stat.exists == false) and (ansible_os_family == "Debian")

        - lineinfile:
            dest: /etc/gitlab/gitlab.rb
            regexp: '^external_url'
            line: "external_url 'http://{{ ansible_host }}'"

        - lineinfile:
            dest: /etc/gitlab/gitlab.rb
            regexp: "backup_keep_time"
            state: absent

        - lineinfile:
            dest: /etc/gitlab/gitlab.rb
            regexp: "backup_keep_time"
            insertafter: "The duration in seconds to keep backups before they are allowed to be deleted"
            line: "gitlab_rails['backup_keep_time'] = 604800"

        - cron:
            minute: 0
            hour: 2
            day: "*"
            month: "*"
            weekday: "*"
            job: "/opt/gitlab/bin/gitlab-rake gitlab:backup:create CRON=1"
            name: gitlab
            state: present
            user: root

        - shell: |
            gitlab-ctl reconfigure
          ignore_errors: true
