- hosts: all
  environment: "{{ proxy_env }}"
  vars:
    loki_version: v1.6.1
    promtail_version: v1.6.1

    loki_url: https://github.com/grafana/loki/releases/download/{{ loki_version }}/loki-linux-amd64.zip
    promtail_url: https://github.com/grafana/loki/releases/download/{{ promtail_version }}/promtail-linux-amd64.zip
  tasks:
    - name: promtail  # {{{
      tags: [ promtail ]
      block:
        - stat:
            path: /usr/local/bin/promtail
          register: p

        - name: 解压promtail安装包
          unarchive:
            copy: false
            src: "{{ promtail_url }}"
            dest: /usr/local/bin
            owner: root
            group: root
            mode: 0755
          when: p.stat.exists == false

        - name: 重命名promtail可执行文件
          command: mv /usr/local/bin/promtail-linux-amd64 /usr/local/bin/promtail
          when: p.stat.exists == false

        - name: 生成promtail配置文件
          template:
            src: files/loki/config/promtail.yml.j2
            dest: /opt/promtail.yml
            mode: 0644
            owner: root
            group: root

        - name: promtail启动命令
          set_fact:
            service_name: prmotail
            start_command: /usr/local/bin/promtail -config.file /opt/promtail.yml

        - name: 生成promtail服务
          template:
            src: files/loki/service/template.service.j2
            dest: /lib/systemd/system/promtail.service
            mode: 0644

        - name: 重新载入systemd
          systemd:
            daemon_reload: true

        - name: 启动promtail服务
          systemd:
            name: promtail
            state: started

        - name: 设置promtail服务开机自启
          systemd:
            name: promtail
            enabled: true
# }}}

    - name: loki # {{{
      tags: loki
      block:
        - stat:
            path: /usr/local/bin/loki
          register: l

        - name: 解压loki安装包
          unarchive:
            copy: false
            src: "{{ loki_url }}"
            dest: /usr/local/bin
            owner: root
            group: root
            mode: 0755
          when: l.stat.exists == false

        - name: 重命名loki可执行文件
          command: mv /usr/local/bin/loki-linux-amd64 /usr/local/bin/loki
          when: l.stat.exists == false

        - name: 生成loki配置文件
          template:
            src: files/loki/config/loki.yml.j2
            dest: /opt/loki.yml
            mode: 0644
            owner: root
            group: root

        - name: loki启动命令
          set_fact:
            service_name: loki
            start_command: /usr/local/bin/loki -config.file /opt/loki.yml

        - name: 生成loki服务
          template:
            src: files/loki/service/template.service.j2
            dest: /lib/systemd/system/loki.service
            mode: 0644

        - name: 重新载入systemd
          systemd:
            daemon_reload: true

        - name: 启动loki服务
          systemd:
            name: loki
            state: started

        - name: 设置loki服务开机自启
          systemd:
            name: loki
            enabled: true
      when: inventory_hostname is match ("^prometheus-server")
# }}}
