##
# 监控工具(Monit)，依赖插件 merge-vars
#
# 归集工具，由原生的 mmonit 改为了 monit_exporter
####
- hosts: all:!off
  vars:
    monit_cycle: "30 start delay 10"
    monit_mail_enabled: true
    monit_mailserver_host: smtp.126.com
    monit_mailserver_port: 465
    monit_webinterface_bind: "{{ ansible_host }}"
    monit_webinterface_port: 2812
    monit_webinterface_enabled: true
    monit_webinterface_acl_rules:
      - monit:monit read-only
    monit_alert_mail_format:
      from: "alert@126.com"
      subject: "[monit] $SERVICE ({{ inventory_hostname }}): $EVENT"
      reply-to: "admin@126.com"
      message: |
        where: {{ ansible_host }} ({{ inventory_hostname }})
        when:  $DATE
        what:  $ACTION

        $DESCRIPTION

        --
        http://{{ ansible_host }}:2812 (monit / monit)
    monit_service_delete_unlisted: true
  pre_tasks:
    - setup:
        gather_subset: min
    - merge_vars:
        merged_var_name: monit_services
        suffix_to_merge: monit_services__to_merge
        expected_type: 'dict'
    - merge_vars:
        merged_var_name: monit_alert_addresses
        suffix_to_merge: monit_alert_addresses__to_merge
        expected_type: 'list'
  roles:
    - { role: leif160519.monit }
