# 卸载ubuntu自带的mysql-8.0 {{{
# Leif160519 @2020年11月2日
- hosts: os.ubuntu
  tags: never, mysql
  vars:
    mysql_root_dir: /var/lib/mysql
    mysql_config_dir: /etc/mysql
    mysql_log_dir: /var/log/mysql
    mysql_autostart_file: /etc/init.d/mysql
    mysql_sock_dir1: /var/run/mysqld
    mysql_sock_dir2: /run/mysqld
    mysql_share_dir: /usr/share/mysql
  tasks:
    - name: 停止mysql服务
      service:
        name: mysql
        state: stopped
        enabled: false
      ignore_errors: yes

    - name: 卸载与mysql相关的所有软件包
      shell: |
        dpkg -l | grep mysql  | awk '{print $2}' | xargs apt-get remove --purge -y
        dpkg -l | grep mysql  | awk '{print $2}' | xargs apt-get autoremove --purge -y
      ignore_errors: yes

    - name: 删除启动文件 # 重复删除
      file:
        path: "{{ mysql_autostart_file }}"
        state: absent

    - name: 删除mysql运行路径
      file:
        path: "{{ mysql_root_dir }}"
        state: absent

    - name: 删除mysql配置文件路径
      file:
        path: "{{ mysql_config_dir }}"
        state: absent

    - name: 删除mysql日志路径 # 重复删除
      file:
        path: "{{ mysql_log_dir }}"
        state: absent

    - name: 删除mysql.sock路径 # mysql卸载时会自动删除，此处也是为了重复删除
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ mysql_sock_dir1 }}"
        - "{{ mysql_sock_dir2 }}"

    - name: 删除其他mysql路径
      file:
        path: "{{ mysql_share_dir }}"
        state: absent

    - name: 清除无用依赖
      apt:
        autoremove: yes

    - name: 清理缓存程序安装包
      shell: apt clean && apt autoclean
      ignore_errors: yes
# }}}

# 载Ubuntu的gnome桌面环境 {{{
#
#
##
# @leif160519 @2020.08.29
####
- name: 卸载gnome环境
  hosts: os.ubuntu.lts
  tags: never, gnome
  tasks:
    - name: 卸载gnome-shell主程序
      apt:
        name: gnome-shell
        state: absent

    - name: 卸载gnome
      apt:
        name: gnome
        state: absent

    - name: 卸载不需要的依赖关系
      apt:
        autoremove: yes

    - name: 彻底删除gnome的相关配置文件
      shell: apt-get purge gnome
      ignore_errors: yes

    - name: 彻底删除残留gnome相关组件
      shell: |
        dpkg -l | grep gnome  | awk '{print $2}' | xargs apt-get remove --purge -y
        dpkg -l | grep gnome  | awk '{print $2}' | xargs apt-get autoremove --purge -y
      ignore_errors: yes

    - name: 清理安装gnome时留下的缓存程序软件包
      shell: apt clean && apt autoclean
      ignore_errors: yes

    - name: 重启生效
      shell: echo "重启生效"
# }}}
