- name: 集中备份账号 # {{{
  tags: backuppc
  hosts: all:!off
  tasks:
    - authorized_key:
        user: root
        state: present
        key: "{{ backuppc_idrsapub }}"
    - known_hosts:
        name: '{{ ansible_host }}'
        key: '{{ ansible_host }} ecdsa-sha2-nistp256 {{ ansible_ssh_host_key_ecdsa_public | default(ansible_ssh_host_key_rsa_public) }}'
      become: true
      become_user: backuppc
      delegate_to: backuppc-server
# }}}

- name: create public user # {{{
  hosts: all:!off
  tags: never, create_public_user
  vars:
    username: public
    groupname: public
    password: public
  tasks:
    - block:
        - group:
            name: "{{ groupname }}"
            system: true
            state: present

        - user:
            name: "{{ username }}"
            system: true
            shell: /bin/bash
            group: "{{ groupname }}"
            createhome: true
            password: "{{ password | password_hash('sha512') }}"
            update_password: always

        - lineinfile:
            dest: /etc/sudoers.d/{{ username }}
            create: true
            line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
            mode: 0440
            owner: root
            group: root
            validate: /usr/sbin/visudo -cf %s
      when: not ( username is match "root" )
# }}}

- name: create readonly user # {{{
  hosts: all:!off
  tags: never, create_readonly_user
  vars:
    username: readonly
    groupname: readonly
    password: readonly
  tasks:
    - block:
        - group:
            name: "{{ groupname }}"
            system: false
            state: present

        - user:
            name: "{{ username }}"
            system: false
            shell: /bin/bash
            group: "{{ groupname }}"
            createhome: true
            password: "{{ password | password_hash('sha512') }}"
            update_password: always

        - file:
            path: /home/{{ username }}/.bin
            state: directory
            owner: "{{ username }}"
            group: "{{ groupname }}"
            mode: 0755

        - lineinfile:
            dest: /home/{{ username }}/.bashrc
            create: true
            line: "{{ item }}"
            mode: 0644
            owner: "{{ username }}"
            group: "{{ groupname }}"
          with_items:
            - PATH=$HOME/.bin
            - export PATH

        - file:
            src: "{{ item }}"
            dest: "/home/{{ username }}/.bin/{{ item | basename }}"
            state: link
            owner: "{{ username }}"
            group: "{{ groupname }}"
            mode: 0755
            force: true
          with_fileglob:
            - /bin/ls
            - /bin/cp
            - /bin/df
            - /bin/grep
            - /bin/more
            - /bin/netstat
            - /bin/ps
            - /bin/pwd
            - /bin/tar
            - /bin/cat
            - /usr/bin/wc
            - /usr/bin/tail
            - /usr/bin/find
            - /usr/bin/less
            - /usr/bin/top
            - /usr/bin/free
            - /usr/bin/du
            - /usr/bin/telnet
            - /usr/bin/head
            - /usr/bin/wget
            - /usr/bin/curl
            - /usr/bin/which
            - /usr/bin/whoami
            - /usr/bin/whereis
            - /usr/bin/who
      when: not ( username is match "root" )
# }}}
